### PR TITLE
Enable automated testing

### PR DESCRIPTION
**Pull request by CromwellEnage**
Also update boost::cnv::cnvbase and boost::cnv::basic_stream to use public interface of Boost.Parameter vice boost::parameter::aux::tag.

### CODE REVIEW

**Comment by yet-another-user** [comment]
Would you mind elaborating what your changes improve or what problems do they solve please? Additional functionality? Additional support? Fixes? So far, I see additional dependencies on boost/mpl and boost/parameter which I do not immediately see as beneficial. Thanks.

**Comment by CromwellEnage** [comment]
In a nutshell, this PR fixes the errors that showed up on the last PR whose commit you merged.  The errors stem from using boost::parameter::aux::tag, a metafunction that is internal to Boost.Parameter and that may therefore be subject to interface and/or implementation changes.  The code changes featured in this PR use the public interface of the ArgumentPack (which models MPL Associative Sequence) to perform the desired assignment operations if the corresponding arguments are available, which was the original intent.

**Comment by yet-another-user** [comment]
1. I merged two "yml" files. Are they related to the Boost testing framework or they are the artifacts of your testing framework? 

2. In the current outstanding pull request I see quite a few changes... some of them style. For ex., "template<typename>" vs. "template <typename>". Was it essential? I acknowledge your differing stylistic preferences. However, that creates more review work for me IMO unnecessarily... and that assumes that I'll be willing to adopt your style... when you decided _not_ to adopt mine. :-)  

3. You state that the "errors stem from"... In the Boost framework the existing code was not causing any errors. Has the Boost framework changed?.. 

4. You state that "boost::parameter::aux::tag... _may_ ... be subject to interface and/or implementation changes". Indeed it may. Is it an _actual_ problem or it is a _potential_ problem? If it is the latter, then I am reluctant introducing voluminous changes without the actual need, sufficient testing and code review. In my view, "do not fix it if it ain't broken".

**Comment by CromwellEnage** [comment]
The metafunction boost::parameter::is_argument_pack is currently only
available in the development branch of https://github.com/boostorg/parameter
and, like the rest of the changes there, won’t be released until Boost 1.70
at the earliest.  But you can always download & unzip into your local
environment, then make sure your compiler searches its include directory
before your main Boost distribution.

**Comment by yet-another-user** [comment]
> The metafunction boost::parameter::is_argument_pack is currently only available in the development branch of https://github.com/boostorg/parameter and, like the rest of the changes there, won’t be released until Boost 1.70 at the earliest.

I suspected so. :-( I am not sure if it is a good idea of "convert" relying on "parameter/development". After all, the idea behind all these changes was to replace the internal parameter API (subject to change). We should not be replacing it with just another subject-to-change API. Agree?

**Comment by CromwellEnage** [comment]
The metafunction *will* be part of Boost.Parameter’s public interface, and
the HTML reference documentation will reflect this.  It just won’t make the
Boost 1.69 release because that’s already closed to major changes.

**Comment by yet-another-user** [comment]
Aha, I went to parameter/develop and see that you are active in that branch. Good. Now I am more inclined to accept your (seemingly bold) "it will" statement. :-) Now, in parameter/develop I also see .travis.yml and appveyor.yml. One is "." prefixed. the other not. Is it intentional? With regard to "convert" I thought you mentioned that appveyor did not work. So, I removed appveyor.yml, right? Wrong?

**Comment by CromwellEnage** [comment]
The naming conventions are imposed by Travis Cl and AppVeyor, so it is intentional.

Some repositories run the appveyor.yml script while others don't, depending on how their owners set the repositories up.  In order to enable automated testing in my own forks, I also need to have Travis Cl and AppVeyor accounts, then add the forked projects to AppVeyor manually (whereas Travis adds the projects automatically if you use "Sign In via GitHub").  I don't know how different the setup requirements are for library maintainers: you should get a better answer from someone like @ericniebler or @pdimov who have more experience.

In the meantime, I'm going to close this PR and submit a new one in order to resolve the branch conflicts.

**Pull request closed without merging**
